"""
setup_ocs.py — BFRt Python configuration script for the OpenOptics OCS switch.

Reads all configuration from openoptics_config.json (generated by backend.py).
Populates the OCS forwarding table and configures only the ports listed in
ocs_fp_layout.
"""

import os
import json

# ── Load config ──────────────────────────────────────────────────────────────

_script_dir = os.path.dirname(os.path.abspath(os.environ.get("SETUP_SCRIPT") or __file__))

def _load_config(script_dir):
    cfg_path = os.path.join(script_dir, 'openoptics_config.json')
    if os.path.exists(cfg_path):
        with open(cfg_path) as f:
            return json.load(f)
    raise FileNotFoundError(f"openoptics_config.json not found in {script_dir}")

_cfg = _load_config(_script_dir)

TOR_NUM = _cfg["TOR_NUM"]
PORT_NUM = _cfg["PORT_NUM"]
SLICE_NUM = _cfg["NB_TIME_SLICES"]

# ── Clear tables ─────────────────────────────────────────────────────────────

bfrt_pipe = bfrt.ocs.pipe

def clear_all(pipe, verbose=True, batching=True):
    global bfrt
    for table_types in (['MATCH_DIRECT', 'MATCH_INDIRECT_SELECTOR'],
                        ['REGISTER'],
                        ['SELECTOR'],
                        ['ACTION_PROFILE']):
        for table in pipe.info(return_info=True, print_info=False):
            if table['type'] in table_types:
                if verbose:
                    print("Clearing table {:<40} ... ".format(table['full_name']),
                          end='', flush=True)
                table['node'].clear(batch=batching)
                if verbose:
                    print('Done')

clear_all(bfrt_pipe, verbose=False)

# ── OCS front-panel layout from config ───────────────────────────────────────
# ocs_fp_layout in JSON: [[tor_id, port_idx, "cage/lane"], ...]
# Build: ocs_fp_layout[tor_id][port_idx] = (cage, lane)

_layout_cfg = _cfg.get("ocs_fp_layout")
if _layout_cfg is None:
    raise ValueError("Missing ocs_fp_layout in openoptics_config.json")

ocs_fp_layout = [[] for _ in range(TOR_NUM)]
for tor_id, port_idx, cage_str in _layout_cfg:
    cage, lane = cage_str.split("/")
    while len(ocs_fp_layout[tor_id]) <= port_idx:
        ocs_fp_layout[tor_id].append(None)
    ocs_fp_layout[tor_id][port_idx] = (int(cage), int(lane))

def get_dev_port(cage, lane=0):
    return bfrt.port.port_hdl_info.get(CONN_ID=cage, CHNL_ID=lane, print_ents=False).data[b'$DEV_PORT']

# Resolve cage/lane to dev_ports
ocs_dev_ports = [
    [get_dev_port(*p) for p in tor_fps if p is not None]
    for tor_fps in ocs_fp_layout
]

# ── Configure only the ports in the layout ───────────────────────────────────

_bw_cfg = _cfg.get("bandwidth", {})
_uplink_gbps = _bw_cfg.get("uplink_gbps", 100)
_uplink_fec = _bw_cfg.get("uplink_fec", "NONE")

speed_dict = {
    '10G': 'BF_SPEED_10G',  '25G': 'BF_SPEED_25G',
    '40G': 'BF_SPEED_40G',  '50G': 'BF_SPEED_50G',
    '100G': 'BF_SPEED_100G',
}
fec_dict = {'NONE': 'BF_FEC_TYP_NONE', 'FC': 'BF_FEC_TYP_FC', 'RS': 'BF_FEC_TYP_RS'}

for tor_fps in ocs_fp_layout:
    for p in tor_fps:
        if p is None:
            continue
        dp = get_dev_port(*p)
        bfrt.port.port.add(
            DEV_PORT=dp,
            SPEED=speed_dict[f'{_uplink_gbps}G'],
            FEC=fec_dict[_uplink_fec],
            AUTO_NEGOTIATION='PM_AN_FORCE_DISABLE',
            PORT_ENABLE=True)

# ── Load OCS table entries from JSON ─────────────────────────────────────────

ocs_table = bfrt_pipe.Ingress.ocs_table

_ocs_json_path = os.path.join(_script_dir, 'ocs_entries.json')
with open(_ocs_json_path) as _f:
    _ocs_payload = json.load(_f)

_count = 0
for e in _ocs_payload["entries"]:
    ingress_dp = ocs_dev_ports[e["ingress_tor"]][e["ingress_port"]]
    egress_dp = ocs_dev_ports[e["egress_tor"]][e["egress_port"]]
    ocs_table.add_with_set_egress_port(
        cur_slice=e["cur_slice"],
        ingress_port=ingress_dp,
        egress_port=egress_dp)
    _count += 1
print(f"[OpenOptics] Loaded {_count} OCS entries from JSON.")

# ── Multicast kickoff — send rotation packets to all OCS ports ───────────────

active_dev_ports = []
for tor_fps in ocs_fp_layout:
    for p in tor_fps:
        if p is not None:
            active_dev_ports.append(get_dev_port(*p))

bfrt.pre.node.add(MULTICAST_NODE_ID=0, MULTICAST_RID=0, MULTICAST_LAG_ID=[], DEV_PORT=active_dev_ports)
bfrt.pre.mgid.add(MGID=1, MULTICAST_NODE_ID=[0], MULTICAST_NODE_L1_XID_VALID=[False], MULTICAST_NODE_L1_XID=[0])

print(f"[OpenOptics] OCS setup complete ({len(active_dev_ports)} ports, {_count} entries).")
