# Generated by Django 4.2.27 on 2026-03-24 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epochs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('topo_image', models.ImageField(upload_to='topos/')),
            ],
        ),
        migrations.CreateModel(
            name='UniformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('depth', models.IntegerField()),
                ('loss_ctr', models.FloatField()),
                ('timestep', models.IntegerField()),
                ('epoch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboardapp.epochs')),
            ],
        ),
    ]
