#!/bin/bash
# OpenOptics ToR switch launcher.
# Reads all parameters from openoptics_config.json (generated by backend.py).
#
# Prerequisites (run once in your shell before invoking this script):
#   source /home/p4/bf-sde-9.12.0/set_sde.bash
#   export SDE_INSTALL=/home/p4/bf-sde-9.12.0/install

set -e

# SDE must be set in the calling shell (source set_sde.bash beforehand)
if [[ -z "$SDE" || -z "$SDE_INSTALL" ]]; then
  echo "Error: SDE and SDE_INSTALL are not set."
  echo "  source /home/p4/bf-sde-9.12.0/set_sde.bash"
  echo "  export SDE_INSTALL=/home/p4/bf-sde-9.12.0/install"
  exit 1
fi

# Project directory (where this script lives)
SCRIPT_DIR=$(dirname "$(realpath "$0")")
cd "$SCRIPT_DIR"

# Read all runtime parameters from openoptics_config.json
CONFIG_JSON="$SCRIPT_DIR/openoptics_config.json"
if [[ ! -f "$CONFIG_JSON" ]]; then
  echo "Error: $CONFIG_JSON not found. Run deployment from the control machine first."
  exit 1
fi
DURATION=$(python3 -c "import json; print(str(json.load(open('$CONFIG_JSON'))['SLICE_DURATION']) + 'us')")
NB_TIME_SLICES=$(python3 -c "import json; print(json.load(open('$CONFIG_JSON'))['NB_TIME_SLICES'])")
TOR_NUM=$(python3 -c "import json; print(json.load(open('$CONFIG_JSON'))['TOR_NUM'])")
PORT_NUM=$(python3 -c "import json; print(json.load(open('$CONFIG_JSON'))['PORT_NUM'])")

# Build the binary
make clean && make || { echo "Build failed"; exit 1; }

# Export setup script path (overridable via env)
export SETUP_SCRIPT="${SETUP_SCRIPT:-$SCRIPT_DIR/setup_tor.py}"

# --daemon flag: set by deploy.py via OPENOPTICS_DAEMON env var
DAEMON_FLAG=""
if [[ "${OPENOPTICS_DAEMON:-0}" == "1" ]]; then
  DAEMON_FLAG="--daemon"
fi

echo "Running ToR: duration=$DURATION nb_time_slices=$NB_TIME_SLICES tor_num=$TOR_NUM port_num=$PORT_NUM daemon=${OPENOPTICS_DAEMON:-0}"
# -E preserves SDE, SDE_INSTALL, SETUP_SCRIPT into the root environment
sudo -E stdbuf -oL ./openoptics_tor "$DURATION" "$NB_TIME_SLICES" "$TOR_NUM" "$PORT_NUM" $DAEMON_FLAG
