"""
setup_tor.py — BFRt Python configuration script for OpenOptics ToR switches.

Run via the BFRt shell after the C++ control plane has loaded the P4 program:
    bfshell -b setup_tor.py

Reads all configuration from openoptics_config.json (generated by backend.py),
then populates match-action tables on the Tofino2 for each logical ToR pipe
hosted on this physical switch.
"""

import os
import sys
import socket
import ipaddress
from scapy.all import *
import setup_util as util
import json

hostname = socket.gethostname()

# Base path: directory containing this script (openoptics-tor/).
# SETUP_SCRIPT is set to the absolute path of this file by run.sh / the C++ binary.
path = os.path.dirname(os.path.abspath(os.environ.get("SETUP_SCRIPT") or __file__))

# ── Configuration from openoptics_config.json ────────────────────────────────
_cfg = util._load_config(path)
TOR_NUM = _cfg["TOR_NUM"]
PORT_NUM = _cfg["PORT_NUM"]
SLICE_NUM = _cfg["NB_TIME_SLICES"]
GUARDBAND = 0    # Extra headroom subtracted from max queue depth (bytes)

# Per-tor hardware config: {tor_id: {...}}
_tors_cfg = {t["tor_id"]: t for t in _cfg.get("tors", [])}
# Physical switches: [{name, tor_ids}, ...]
_switches_cfg = _cfg.get("physical_switches", [])
# Bandwidth defaults
_bw_cfg = _cfg.get("bandwidth", {})

# Queue-depth emulation: the data plane drains a virtual queue counter every
# UPDATE_INTERVAL_NS nanoseconds by subtracting qdiff bytes per port.
# At 100G, one byte transmits in 0.08ns, so 50ns drains 50 / 0.08 = 625 bytes.
UPDATE_INTERVAL_NS = 50
LINK_GBPS = 100
qdiff = int(UPDATE_INTERVAL_NS * LINK_GBPS / 8)  # bytes drained per drain tick, per port

# max_qdepth (bytes per port) is computed at runtime from slice_duration_us
max_qdepth = -1

ETHERTYPE_IPV4 = 0x0800
ETHERTYPE_IPV6 = 0x86dd

# Runtime globals populated by get_arguments()
slice_duration_us = -1   # slice length in microseconds

# ── Switch self-MAC table (indexed by tor_id) ──────────────────────────────────
# Used to detect packets destined for the local ToR's server
self_mac = [0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17]

# Logical port IDs used in the P4 routing tables (not real dev_ports)
electrical_port    = 0xaa  # Sentinel: route via electrical fallback link
to_elec_port       = 0xaa  # Same sentinel used in egress port table
to_server_logic_port = 0xff  # Sentinel: deliver to local server


# ── Helpers ───────────────────────────────────────────────────────────────────

def _resolve_devport(cage_lane_str):
    """Resolve 'cage/lane' string to a Tofino dev_port number at runtime."""
    cage, lane = cage_lane_str.split("/")
    return bfrt.port.port_hdl_info.get(
        CONN_ID=int(cage), CHNL_ID=int(lane), print_ents=False
    ).data[b'$DEV_PORT']


def add_port_config(port_config):
    """Add a single front-panel port to the BFRt port table.

    port_config is a tuple: (port_str, speed_str, fec_str, an_int)
      port_str  : "cage/lane", e.g. "25/0".  Use '-' as lane to configure all
                  lanes for the given speed (e.g. 4 lanes for 25G QSFP).
      speed_str : '10G' | '25G' | '40G' | '50G' | '100G'
      fec_str   : 'NONE' | 'FC' | 'RS'
      an_int    : 0=default, 1=force-enable, 2=force-disable auto-negotiation
    """
    speed_dict = {
        '10G': 'BF_SPEED_10G',  '25G': 'BF_SPEED_25G',
        '40G': 'BF_SPEED_40G',  '50G': 'BF_SPEED_50G',
        '100G': 'BF_SPEED_100G',
    }
    fec_dict = {'NONE': 'BF_FEC_TYP_NONE', 'FC': 'BF_FEC_TYP_FC', 'RS': 'BF_FEC_TYP_RS'}
    an_dict  = {0: 'PM_AN_DEFAULT', 1: 'PM_AN_FORCE_ENABLE', 2: 'PM_AN_FORCE_DISABLE'}
    lanes_dict = {'10G': (0,1,2,3), '25G': (0,1,2,3), '40G': (0,), '50G': (0,2), '100G': (0,)}

    conf_port = int(port_config[0].split('/')[0])
    lane      = port_config[0].split('/')[1]
    conf_speed = speed_dict[port_config[1]]
    conf_fec   = fec_dict[port_config[2]]
    conf_an    = an_dict[port_config[3]]

    if lane == '-':
        for l in lanes_dict[port_config[1]]:
            dp = bfrt.port.port_hdl_info.get(CONN_ID=conf_port, CHNL_ID=l, print_ents=False).data[b'$DEV_PORT']
            bfrt.port.port.add(DEV_PORT=dp, SPEED=conf_speed, FEC=conf_fec, AUTO_NEGOTIATION=conf_an, PORT_ENABLE=True)
    else:
        conf_lane = int(lane)
        dp = bfrt.port.port_hdl_info.get(CONN_ID=conf_port, CHNL_ID=conf_lane, print_ents=False).data[b'$DEV_PORT']
        bfrt.port.port.add(DEV_PORT=dp, SPEED=conf_speed, FEC=conf_fec, AUTO_NEGOTIATION=conf_an, PORT_ENABLE=True)


# ── Table clear helper ─────────────────────────────────────────────────────────

def clear_all(pipe, pipe_id, verbose=True, batching=True):
    """Clear all BFRt tables for a specific pipe in dependency order.

    Order matters: MATCH tables (which reference selectors/profiles) must be
    cleared before SELECTOR groups, which must be cleared before ACTION_PROFILE
    members.
    """
    global bfrt

    for table_types in (
        ['MATCH_DIRECT', 'MATCH_INDIRECT_SELECTOR'],
        ['REGISTER'],
        ['SELECTOR'],
        ['ACTION_PROFILE'],
    ):
        for table in pipe.info(return_info=True, print_info=False):
            if table['type'] in table_types:
                if verbose:
                    print("Clearing table {:<40} ... ".format(table['full_name']),
                          end='', flush=True)
                table['node'].clear(pipe=pipe_id, batch=batching)
                if verbose:
                    print('Done')


def init_asymmetric_mode():
    """Set all match tables to asymmetric mode (per-pipe independent entries).

    Must be called once before setup_tor() loops over pipes.  In symmetric mode
    (the default) every table write fans out to all physical pipes; asymmetric
    mode restricts each write to the pipe specified by the pipe= argument.
    """
    tor_pipe = bfrt.openoptics_tor.tor_pipe
    for table_info in tor_pipe.info(return_info=True, print_info=False):
        if table_info['type'] in ('MATCH_DIRECT', 'MATCH_INDIRECT_SELECTOR'):
            table_info['node'].symmetric_mode_set(False)


# ── Traffic-manager port-group helpers ────────────────────────────────────────

def get_pg_id(dev_port):
    """Return the TM port-group ID for a given dev_port.

    Each Tofino2 pipe has 128 dev_ports arranged in groups of 8, giving 16
    port groups (pg_id 0–15) per pipe.
    """
    return (dev_port % 128) >> 3


def get_pg_queue(dev_port, qid):
    """Return the TM per-MAC queue index for (dev_port, qid).

    Each lane within a port group has 16 physical queues; the MAC queue ID is
    lane * 16 + qid.
    """
    lane = dev_port % 8
    return lane * 16 + qid


# ── AFC (Advanced Flow Control) packet definition ─────────────────────────────

class AFC(Packet):
    """Scapy packet for Tofino2 AFC pause/resume messages.

    Fields:
      afc        : 1 = AFC mode (always 1 here)
      tm_pipe_id : TM pipe index (0–3)
      tm_mac_id  : TM port-group ID (pg_id)
      pad        : reserved padding
      tm_mac_qid : per-MAC queue index (pg_queue)
      credit     : 1 = pause (stop sending), 0 = resume (allow sending)
    """
    name = "adv_flow_ctl"
    fields_desc = [
        BitField("afc",        0,  1),
        BitField("tm_pipe_id", 0,  2),
        BitField("tm_mac_id",  0,  4),
        BitField("pad",        0,  3),
        BitField("tm_mac_qid", 0,  7),
        BitField("credit",     0, 15),
    ]


# ── Main per-ToR setup routine ─────────────────────────────────────────────────

def setup_tor(pipe_id, tor_id):
    """Populate all P4 tables for one ToR pipe.

    Args:
        pipe_id         : Physical Tofino2 pipe index (0–3); used to scope all
                          table writes to the correct pipe.  init_asymmetric_mode()
                          must be called before the first setup_tor() call.
        tor_id          : Logical ToR index (0–7)
    """
    tor_pipe = bfrt.openoptics_tor.tor_pipe
    tcfg = _tors_cfg[tor_id]

    # ── Resolve physical ports from config cage/lane strings ────────────────
    ocs_devports = [_resolve_devport(p) for p in tcfg["ocs_ports"]]
    server_devports = [_resolve_devport(p) for p in tcfg.get("server_ports", [])]
    elec_devport = _resolve_devport(tcfg["electrical_port"]) if "electrical_port" in tcfg else None
    server_mac = tcfg.get("server_mac")
    has_server = bool(server_devports and server_mac)

    # Bandwidth/FEC from config with per-tor overrides
    uplink_gbps = _bw_cfg.get("uplink_gbps", 100)
    uplink_fec = tcfg.get("uplink_fec", _bw_cfg.get("uplink_fec", "NONE"))
    server_gbps = _bw_cfg.get("server_gbps", 100)
    server_fec = tcfg.get("server_fec", _bw_cfg.get("server_fec", "NONE"))
    elec_gbps = _bw_cfg.get("electrical_gbps", 100)
    elec_fec = tcfg.get("electrical_fec", _bw_cfg.get("electrical_fec", "NONE"))

    # ── Step 1: Clear all tables and configure physical ports ─────────────────
    clear_all(tor_pipe, pipe_id, verbose=False)

    for port_str in tcfg["ocs_ports"]:
        add_port_config((port_str, f'{uplink_gbps}G', uplink_fec, 2))
    for port_str in tcfg.get("server_ports", []):
        add_port_config((port_str, f'{server_gbps}G', server_fec, 0))
    if "electrical_port" in tcfg:
        add_port_config((tcfg["electrical_port"], f'{elec_gbps}G', elec_fec, 2))

    # MAC rewrite table for packets forwarded to the local server
    if has_server:
        set_server_mac = tor_pipe.Ingress.routing.set_server_mac
        set_server_mac.add_with_to_server(
            pipe=pipe_id,
            ucast_egress_port=server_devports[0],
            server_mac_addr=server_mac)

    # ── Step 3: Queue-depth emulation registers ───────────────────────────────
    # The P4 program tracks a virtual per-port queue depth to enforce lossless
    # admission control.  These registers set the initial maximum depth (derived
    # from slice_duration) and the per-interval drain amount (qdiff).

    # Global maximum queue depth threshold (used while port is in active slice)
    for port in range(PORT_NUM):
        getattr(tor_pipe.Ingress.queue_mgr, f"p{port}_max_qdepth").set_default(
            value=max_qdepth)

    # Reduced threshold used when a port-queue is in its paused (inactive) slice.
    for port in range(PORT_NUM):
        getattr(getattr(tor_pipe.Ingress.routing, f"tb_read_p{port}_max_qdepth"),
                f"set_default_with_read_p{port}_paused_max_qdepth_action")(
            pipe=pipe_id, max_qdepth=max_qdepth)

    # Lossless drain rate (bytes subtracted per interval from the lossless counter)
    for port in range(PORT_NUM):
        getattr(tor_pipe.Ingress.queue_mgr, f"p{port}_lossless_qdepth_diff").set_default(
            value=qdiff)

    # Standard drain rate (bytes subtracted per interval from the normal counter)
    for port in range(PORT_NUM):
        getattr(tor_pipe.Ingress.queue_mgr, f"p{port}_qdepth_diff").set_default(
            value=qdiff)

    # ── Step 4: Per-port slice-to-rank mapping (drain path) ───────────────────
    # Drain fires for all cur_slice values including guardbands; guardband slices
    # have no active qid, so fall back to rank 0 — drain on a paused qid is a no-op.
    for port in range(PORT_NUM):
        tb_add = getattr(
            getattr(tor_pipe.Ingress.queue_mgr, f"tb_compute_p{port}_active_rank"),
            f"add_with_compute_p{port}_active_rank")
        for slice_id in range(SLICE_NUM):
            try:
                rank = util.slice_to_rank(tor_id, port, slice_id)
            except ValueError:
                rank = 0
            tb_add(pipe=pipe_id, cur_slice=slice_id, computed_rank=rank)

    # ── Step 6: Frame-size adjustment for optics encapsulation ───────────────
    tb_adjust = tor_pipe.Ingress.routing.tb_adjust_optics_frame_size
    tb_adjust.add_with_add_ipv4_length(
        pipe=pipe_id, ether_type=ETHERTYPE_IPV4, adjustment=12 + 12 + 14 + 22)
    tb_adjust.add_with_add_ipv6_length(
        pipe=pipe_id, ether_type=ETHERTYPE_IPV6, adjustment=14 + 22)

    # ── Step 7: Per-port slice-to-rank mapping (routing/enqueue pipeline) ─────
    # Skip guardband slices — a packet never gets send_slice = guardband.
    for port in range(PORT_NUM):
        tb_add = getattr(
            getattr(tor_pipe.Ingress.routing, f"tb_compute_p{port}_rank"),
            f"add_with_compute_p{port}_rank")
        for slice_id in range(SLICE_NUM):
            try:
                rank = util.slice_to_rank(tor_id, port, slice_id)
            except ValueError:
                continue
            tb_add(pipe=pipe_id, send_slice=slice_id, computed_rank=rank)

    # ── Step 8: Slice-reset triggers per port ────────────────────────────────
    # Table keyed on (cur_slice, ingress_port) — sets p{port}_is_new_slice=1
    # only on port P's own uplink rotation at a window-start slice. Prevents
    # cross-port contamination (rotations multicast to every uplink).
    for port in range(PORT_NUM):
        tb_reset = getattr(
            getattr(tor_pipe.Ingress.queue_mgr, f"tb_set_new_slice_for_p{port}"),
            f"add_with_set_p{port}_is_new_slice")
        for slice_id in util.find_all_reset_slices(tor_id, port):
            tb_reset(pipe=pipe_id, cur_slice=slice_id,
                     ingress_port=ocs_devports[port])

    # ── Step 9: Primary routing tables ────────────────────────────────────────
    # Two tables can coexist:
    #   time_flow_table_per_hop   — one-hop-at-a-time forwarding (routing_mode="Per-hop")
    #   time_flow_table_source    — source-routed paths; 2-hop paths pack the
    #                               second hop into hdr.sr_entry at the source ToR
    # A given (cur_slice, dst_group) may live in either table; the source table
    # takes priority at runtime (see routing.p4 apply block).
    time_flow_table_per_hop = tor_pipe.Ingress.routing.time_flow_table_per_hop
    time_flow_table_source  = tor_pipe.Ingress.routing.time_flow_table_source

    _tor_json_path = os.path.join(path, f'tor_entries_tor{tor_id}.json')
    with open(_tor_json_path) as _f:
        _tor_payload = json.load(_f)

    _per_hop_count = 0
    for e in _tor_payload.get("per_hop_routing_entries", []):
        time_flow_table_per_hop.add_with_set_send_slice(
            pipe=pipe_id,
            cur_slice=e["cur_slice"],
            dst_group=e["dst_group"],
            port=e["port"],
            next_tor=e["next_tor"],
            slot=e["slot"],
            alternate_port=e["alternate_port"],
            alternate_next_tor=e["alternate_next_tor"],
            alternate_slot=e["alternate_slot"],
            alt_rank=util.slice_to_rank(tor_id, e["alternate_port"],
                                        e["alternate_slot"]))
        _per_hop_count += 1

    _sr_count = 0
    for e in _tor_payload.get("source_routing_entries", []):
        hops = e["hops"]
        if len(hops) == 1:
            h0 = hops[0]
            time_flow_table_source.add_with_set_sr_1_hops(
                pipe=pipe_id,
                cur_slice=e["cur_slice"],
                dst_group=e["dst_group"],
                port=h0["send_port"],
                slot=h0["send_slice"],
                next_tor=h0["next_tor"])
        elif len(hops) == 2:
            h0, h1 = hops[0], hops[1]
            time_flow_table_source.add_with_set_sr_2_hops(
                pipe=pipe_id,
                cur_slice=e["cur_slice"],
                dst_group=e["dst_group"],
                port=h0["send_port"],
                slot=h0["send_slice"],
                next_tor=h0["next_tor"],
                hop1_cur_node=h1["cur_node"],
                hop1_send_slice=h1["send_slice"],
                hop1_send_port=h1["send_port"],
                hop1_next_tor=h1["next_tor"])
        else:
            raise ValueError(
                f"time_flow_table_source only supports 1- or 2-hop paths, "
                f"got {len(hops)} hops for ToR {tor_id} entry "
                f"(cur_slice={e['cur_slice']}, dst_group={e['dst_group']})")
        _sr_count += 1

    # ── Step 9b: Node-indexed forwarding table (cal_port_slice_to_node) ──────
    # Resolves "forward to node X" sentinels (send_slice == 255) into concrete
    # (port, slice) at the transit ToR.  Used by VLB routing.
    cal_port_slice_to_node = tor_pipe.Ingress.routing.cal_port_slice_to_node
    _cal_count = 0
    for e in _tor_payload.get("node_to_port_slice_entries", []):
        cal_port_slice_to_node.add_with_resolve_node_to_port(
            pipe=pipe_id,
            send_port=e["dst_node"],
            cur_slice=e["arrival_ts"],
            resolved_port=e["send_port"],
            resolved_slice=e["send_slice"],
            resolved_next_tor=e["next_tor"])
        _cal_count += 1

    # ── Step 9c: Random port table (tb_random_to_port) ───────────────────────
    # Maps every random byte (0–255) to a port index via modular reduction,
    # giving a uniform distribution for any PORT_NUM.  Used by the generic
    # send_port == 0xff sentinel (e.g. VLB with random=True).
    tb_random_to_port = tor_pipe.Ingress.routing.tb_random_to_port
    for r in range(256):
        tb_random_to_port.add_with_set_random_port(
            pipe=pipe_id, random_id=r, port=r % PORT_NUM)

    print(f"[OpenOptics] Loaded {_per_hop_count} per-hop, {_sr_count} "
          f"source-routing, {_cal_count} node-to-port entries "
          f"for ToR {tor_id} (pipe {pipe_id}) from JSON.")

    # Packets whose dst MAC matches the local ToR's self_mac are sent to server
    tb_check_to_server = tor_pipe.Ingress.routing.tb_check_to_server
    tb_check_to_server.add_with_set_to_server_port(pipe=pipe_id, dst_group=self_mac[tor_id])

    # ── Step 9b: IP → dst-MAC rewrite at source ToR ──────────────────────────
    # Eliminates the need for servers to install magic static ARP entries.
    # Each entry maps a remote data-plane IP → magic dst MAC (0x10 + dst_tor_id);
    # the existing dst_group = (bit<16>)hdr.ethernet.dst_addr then picks up the
    # rewritten value, so downstream logic (time_flow_table_*, tb_check_to_server)
    # is unchanged.
    _routing_node = tor_pipe.Ingress.routing
    _has_v4_table = hasattr(_routing_node, 'tb_ipv4_to_dst_mac')
    _has_v6_table = hasattr(_routing_node, 'tb_ipv6_to_dst_mac')
    if not (_has_v4_table or _has_v6_table):
        print(
            f"[OpenOptics] WARN: P4 program lacks tb_ipv4_to_dst_mac and "
            f"tb_ipv6_to_dst_mac; skipping IP→dst-MAC rewrite for ToR {tor_id} "
            f"(servers must install static ARP entries with magic ToR MACs)."
        )
    else:
        _ip2mac_entries = _tor_payload.get("ip_to_mac_entries", [])
        tb_v4 = _routing_node.tb_ipv4_to_dst_mac if _has_v4_table else None
        tb_v6 = _routing_node.tb_ipv6_to_dst_mac if _has_v6_table else None

        _v4_count = 0
        _v6_count = 0
        for _e in _ip2mac_entries:
            dst_mac = 0x000000000010 + int(_e["dst_node"])
            ip_str = _e["ip"]
            if ":" in ip_str:
                if tb_v6 is None:
                    continue
                ip_int = int(ipaddress.IPv6Address(ip_str))
                tb_v6.add_with_rewrite_dst_mac_v6(
                    pipe=pipe_id, dst_addr=ip_int, dst_mac=dst_mac)
                _v6_count += 1
            else:
                if tb_v4 is None:
                    continue
                ip_int = int(ipaddress.IPv4Address(ip_str))
                tb_v4.add_with_rewrite_dst_mac(
                    pipe=pipe_id, dst_addr=ip_int, dst_mac=dst_mac)
                _v4_count += 1
        print(
            f"[OpenOptics] Loaded {_v4_count} IPv4 + {_v6_count} IPv6 "
            f"dst-MAC rewrite entries for ToR {tor_id}."
        )

    # ── Step 10: Egress port mapping (logical port → physical dev_port) ───────
    tb_set_egress_port = tor_pipe.Ingress.routing.tb_set_egress_port
    for i in range(PORT_NUM):
        tb_set_egress_port.add_with_set_egress_port(
            pipe=pipe_id, send_port=i, port=ocs_devports[i])
    if has_server:
        tb_set_egress_port.add_with_set_egress_port(
            pipe=pipe_id, send_port=to_server_logic_port, port=server_devports[0])
    if elec_devport is not None:
        tb_set_egress_port.add_with_set_egress_port(
            pipe=pipe_id, send_port=to_elec_port, port=elec_devport)
        tb_set_elec_hop = tor_pipe.Ingress.routing.tb_set_elec_hop
        tb_set_elec_hop.add_with_set_elec_hop(pipe=pipe_id, send_port=to_elec_port, elechop=0)

    # ── Step 11: AFC pause/resume table (set_afc_tb) ──────────────────────────
    set_afc_tb = tor_pipe.Ingress.queue_mgr.set_afc_tb

    def gen_pause_afc_msg(port, q):
        """Build an AFC pause message for (port, queue). credit=1 means stop."""
        return AFC(
            afc=1,
            tm_pipe_id=pipe_id,
            tm_mac_id=get_pg_id(ocs_devports[port]),
            tm_mac_qid=get_pg_queue(ocs_devports[port], q),
            credit=1)

    def gen_resume_afc_msg(port, q):
        """Build an AFC resume message for (port, queue). credit=0 means go."""
        return AFC(
            afc=1,
            tm_pipe_id=pipe_id,
            tm_mac_id=get_pg_id(ocs_devports[port]),
            tm_mac_qid=get_pg_queue(ocs_devports[port], q),
            credit=0)

    def pause_port_queue_at_slice(port, queue, slice_id, app_id, ingress_port):
        msg = gen_pause_afc_msg(port, queue)
        set_afc_tb.add_with_set_afc(
            pipe=pipe_id,
            app_id=app_id, slice_id=slice_id, ingress_port=ingress_port,
            afc_msg=int.from_bytes(bytes(msg), "big"))

    def resume_port_queue_at_slice(port, queue, slice_id, app_id, ingress_port):
        msg = gen_resume_afc_msg(port, queue)
        set_afc_tb.add_with_set_afc(
            pipe=pipe_id,
            app_id=app_id, slice_id=slice_id, ingress_port=ingress_port,
            afc_msg=int.from_bytes(bytes(msg), "big"))

    # AFC entries: iterate connection windows directly. qid = window's rank
    # (routed through util.window_to_qid → scaling hook for future bucketing).
    #   - Ongoing (app_id=3): rotation pktgen enters on the OCS-facing uplink.
    #   - Kickoff (app_id=1): ToR's own pktgen source port = 6.
    for port in range(PORT_NUM):
        for (start, pause, _dst) in util.find_connection_windows(tor_id, port):
            qid = util.slice_to_rank(tor_id, port, start)

            pause_port_queue_at_slice(
                port=port, queue=qid, slice_id=pause, app_id=3,
                ingress_port=ocs_devports[port])
            print(f"pause  port {port} qid {qid} at slice {pause}")

            resume_port_queue_at_slice(
                port=port, queue=qid, slice_id=start, app_id=3,
                ingress_port=ocs_devports[port])
            print(f"resume port {port} qid {qid} at slice {start}")

            # Kickoff one-shot initial pause — fired once at boot from ToR port 6.
            pause_port_queue_at_slice(
                port=port, queue=qid, slice_id=pause, app_id=1,
                ingress_port=6)


# ── Argument parsing ──────────────────────────────────────────────────────────

def get_arguments():
    """Read SLICE_DURATION from openoptics_config.json (already loaded as _cfg).

    Sets globals:
        slice_duration_us (int): slice length in microseconds
        max_qdepth (int): max bytes a single port-queue can buffer in one slice
                          at LINK_GBPS, minus GUARDBAND.
    """
    global slice_duration_us, max_qdepth

    slice_duration_us = _cfg["SLICE_DURATION"]
    # Bytes one port can transmit in one slice at LINK_GBPS:
    #   slice_ns × Gbps / 8 = (slice_us × 1000) × LINK_GBPS / 8
    slice_duration_ns = slice_duration_us * 1000
    max_qdepth = int(slice_duration_ns * LINK_GBPS / 8) - GUARDBAND


# ── Entry point ───────────────────────────────────────────────────────────────

get_arguments()

# Determine which tors this switch hosts from config
_my_tor_ids = None
for _sw in _switches_cfg:
    if _sw["name"] == hostname or _sw["name"] in hostname:
        _my_tor_ids = _sw["tor_ids"]
        break

if _my_tor_ids is None:
    print(f"[OpenOptics] ERROR: hostname '{hostname}' not found in config. "
          f"Known switches: {[s['name'] for s in _switches_cfg]}")
    sys.exit(1)

# Dump-only mode: when OPENOPTICS_DUMP_SR=1 is set in the environment, skip
# the normal setup path and only dump the SR diagnostic counters. This lets
# external callers get a runtime snapshot via the same bfshell -b invocation
# that deploy.py uses for setup (which is the only mode where bfshell reliably
# runs Python scripts end-to-end on this SDE).
if os.environ.get("OPENOPTICS_DUMP_SR") == "1":
    tor_pipe = bfrt.openoptics_tor.tor_pipe
    print("[OpenOptics] === BEGIN SR COUNTER DUMP ===")
    for _pid in [0, 1, 2, 3]:
        print("[OpenOptics] -- verify_sr_cur_node pipe %d --" % _pid)
        try:
            tor_pipe.Ingress.routing.verify_sr_cur_node.dump(pipe=_pid, from_hw=True)
        except Exception as _e:
            print("[OpenOptics] ERROR:", _e)
        print("[OpenOptics] -- time_flow_table_source pipe %d --" % _pid)
        try:
            tor_pipe.Ingress.routing.time_flow_table_source.dump(pipe=_pid, from_hw=True)
        except Exception as _e:
            print("[OpenOptics] ERROR:", _e)
    print("[OpenOptics] === END SR COUNTER DUMP ===")
    sys.exit(0)

# Normal setup path: set all match tables to asymmetric mode so each pipe
# can hold independent entries (per-ToR routing, port mappings, etc.)
init_asymmetric_mode()

for tor_id in _my_tor_ids:
    pipe_id = _tors_cfg[tor_id].get("pipe_id")
    if pipe_id is None:
        print(f"[OpenOptics] ERROR: no pipe_id for tor_id {tor_id}")
        sys.exit(1)
    setup_tor(pipe_id=pipe_id, tor_id=tor_id)

print(f"[OpenOptics] Setup complete on {hostname} (tors: {_my_tor_ids})")
