import os
import json
import numpy as np


def _load_config(script_dir):
    """Load runtime config from openoptics_config.json (generated by backend.py)."""
    cfg_path = os.path.join(script_dir, 'openoptics_config.json')
    if not os.path.exists(cfg_path):
        raise FileNotFoundError(
            f"openoptics_config.json not found in {script_dir}. "
            f"This file is generated by backend.py during deployment."
        )
    with open(cfg_path) as f:
        return json.load(f)


_cfg = _load_config(os.path.dirname(os.path.abspath(__file__)))
TOR_NUM = _cfg["TOR_NUM"]
PORT_NUM = _cfg["PORT_NUM"]
SLICE_NUM = _cfg["NB_TIME_SLICES"]

_schedule_dir = os.path.dirname(os.path.abspath(__file__))
_schedule_path = os.path.join(_schedule_dir, 'schedule.txt')
schedule = np.loadtxt(_schedule_path, dtype=int)

active_slices = range(0, SLICE_NUM, 2)

def previous_slice(slice_id : int):
    return (slice_id + SLICE_NUM - 1) % SLICE_NUM

def find_dst_with_valid_slice(src:int, port:int, slice:int):
    #print(schedule)
    
    #print(f"input {src} {port} {slice}")
    coloum = src * 4 + port
    #print(f"coloum {coloum} slice {slice}")
    dst = schedule[slice][coloum]
    if dst == -1:
        slice = (slice+1)%SLICE_NUM
        dst = schedule[slice][coloum]
    #print(f"dst {dst}")
    assert dst != -1
    #return 0, 0
    return slice, dst

def dst_to_port_slice(src : int, dst : int):
    
    coloum = src * PORT_NUM
    #print(schedule.T[coloum])
    connection_for_port = schedule.T[coloum : coloum + PORT_NUM].tolist()

    #print(connection_for_port)

    slice_port = []

    for port, dst_list in enumerate(connection_for_port):
        if dst in dst_list:
            #if src == 0:
            #    print(f"dst {dst}, port {port}")
            start = dst_list.index(dst)
            if start == 0 and dst_list[-1] != -1: #0 is not when connection to dst starts
                half_length = int(len(dst_list)/2)
                start = dst_list[half_length::].index(dst) + half_length

            for slice_id in range(SLICE_NUM):
                if connection_for_port[port][slice_id] == dst: # there is direct link
                    slice_port.append((slice_id, slice_id, port))
                else:
                    slice_port.append((slice_id, start, port))

    #print(f"connection {connection_for_port}, dst {dst}")
    #print(slice_port)

    return slice_port

electrical_port = 0xaa

def find_direct_port_slice_or_electrical(src : int, dst : int):
    
    coloum = src * PORT_NUM
    #print(schedule.T[coloum])
    connection_for_port = schedule.T[coloum : coloum + PORT_NUM].tolist()

    #print(connection_for_port)

    slice_port = []

    for port, dst_list in enumerate(connection_for_port):
        if dst in dst_list:
            start = dst_list.index(dst)
            if start == 0 and dst_list[-1] != -1: #0 is not when connection to dst starts
                half_length = int(len(dst_list)/2)
                start = dst_list[half_length::].index(dst) + half_length

            for slice_id in range(SLICE_NUM):
                if connection_for_port[port][slice_id] == dst: # there is direct link
                    slice_port.append((slice_id, slice_id, port))
                else:
                    slice_port.append((slice_id, start, electrical_port))

    return slice_port


def find_connection_windows(src: int, port: int):
    """Scan schedule column for (src, port); return [(start, pause, dst), ...]
    one tuple per connection window in the rotation.

    - start: first slice where the port actively connects to dst
    - pause: guardband slice (schedule value -1) closing the window
    - dst:   tor id this window connects to
    """
    col = src * PORT_NUM + port
    connection = schedule.T[col].tolist()
    guardbands = [s for s in range(SLICE_NUM) if connection[s] == -1]
    if not guardbands:
        raise ValueError(f"No guardbands for tor={src} port={port}")
    windows = []
    for i, pause in enumerate(guardbands):
        prev_pause = guardbands[i - 1] if i > 0 else guardbands[-1]
        start = (prev_pause + 1) % SLICE_NUM
        s, dst = start, None
        for _ in range(SLICE_NUM):
            if connection[s] != -1:
                dst = connection[s]
                break
            s = (s + 1) % SLICE_NUM
        if dst is None:
            raise ValueError(f"Empty window for tor={src} port={port}")
        windows.append((start, pause, dst))
    return windows


def find_all_reset_slices(src: int, port: int):
    """Window-start slices — where max_lossless_qdepth resets on this port."""
    return {w[0] for w in find_connection_windows(src, port)}


# --- Window → qid mapping (the scalability hook) -----------------------------
# Today: 1:1 identity. Tomorrow: replace with a bucketing function to reuse
# qids across temporally disjoint windows. Downstream code (slice_to_rank,
# AFC loop, active-rank population) goes through this abstraction, so scaling
# changes stay localized here.
def window_to_qid(src: int, port: int, window_idx: int):
    """Map a window index to a TM qid on (src, port). Identity for now."""
    return window_idx


def num_queues(src: int, port: int):
    """Number of distinct qids used on (src, port)."""
    n = len(find_connection_windows(src, port))
    return len({window_to_qid(src, port, i) for i in range(n)})


def slice_to_rank(src: int, port: int, slice_id: int):
    """qid whose AFC-unpaused interval covers slice_id.

    Window q's unpaused interval is [start_q, pause_q) — AFC resumes qid q
    at start_q and pauses at pause_q (guardband, where egress is blocked).
    Strict `< pause` raises on a guardband slice rather than silently
    returning the prior qid.
    """
    for idx, (start, pause, _) in enumerate(find_connection_windows(src, port)):
        if start <= pause:
            hit = (start <= slice_id < pause)
        else:
            hit = (slice_id >= start or slice_id < pause)
        if hit:
            return window_to_qid(src, port, idx)
    raise ValueError(f"slice {slice_id} not mapped on tor={src} port={port}")
